language: go

go:
  - 1.6
  - tip

script:
  - make

matrix:
  allow_failures:
    - go: tip

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "NigbjyGjIJ8FcM1cMwhoSKh7Gror10Fj0AiMAntMFlHm0HRJKyq80iMYepecu2UgzoWDZio3XgTgfdcKuuhD/Y9T/10W625IVlmlzBKuuFem8UJnw90x0GlX9gRckl/mE/arIN1fLKs8olnbIhceH3gtTi8yygCZCJpnjLkgASZvmGaHAibAymEEuMSCtgv+yYUVwPn5dlhrXtKiotD8bLY4FEqpFBOquzdZAUBejTRiO2QUrSsOjiuQ8EFX5sMIYzFs6gKTflDTwFUa11LJJHq58+mPB1V9SOecWIS0tV+4EeySIMER21h4ckIROHcSc1sMFm0XtQhTtbzQ2FxtszhLM8i9mhsxVThSrROK6i/MTEepE6nZlLLE3JbcotGmo+r/yO7H2gijoyE7MSdTDLX6aWj8runADfl116PPiHIXqQtVgG9qSZywukVTPbuVqGQbd6+PknLcBwwghkfamamTFe5KTUREkdPUvdYGPloO/El3J3CTn9esgjNZIJCxhhPe1Dypy9gRIrJi5WhiigFtfINEHzN8rKmMXRYhOY01qsrMT9SWA1De8yLNWiQOc564hlkPwFafMhRE1//SgJIiC2dMVaWMidl1h72RwVxxDXuEnHc0RdEFz7MUw+78TxD3zoJbTHxmA9AxB40cGuFmSoUnxJiVOXPrchLLXzI="
  file_glob: true
  file: release/akamai-gtm_*
  on:
    repo: Comcast/akamai-gtm
    tags: true
