language: go

go:
  - 1.6
  - tip

script:
  - make

matrix:
  allow_failures:
    - go: tip

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ttyGRO+DWTm3CZD5cTboC4qlwjP6/CaI0yJyLhyGGEy/uVH8Ul2gErMDPivA903Hw3mhJd9Yfw+p3b8zJKRBwKy3U34CSrk7uQvzhWs4BH/21xmxZKYmB4hjs930ecf+QuzzkFvBq/gSDGblkhKvgfdxRezSNeTJCsSMeE3QzsFFrXyPow6bQ1NuoVJ1unbWXZNIQAQ7EWKEW20Jl7MNhWmDJK781g36hoxz3Vfyy4XZr37FZgLcNJeZWls4JnzNNwi5nb4yWQy/hfRfBBXkcU32fH+RgCv7+g7uIgypDtNp9dL0WWVK/rof2CkSIshuffI6AZIaCq4kK5kyCICLmsGK+Q1FEkFXnCKpzRQ5F7818aKo5vjVxK+wYE8QvB7FxlRpDwKDUlnIvBv43ZwVBD7Xvnl5xeHY5yl7eS+PiJfA2GsV/yriAi6a4jJ/z5EHQBloLS7sfafQ9YL09hk4egGfIXQQR2Pzhzc4+NmPmEY1O1gdgXjCQ28GJYrpIjhENjMDJqtVd1tFGehJAbp5hF0Dak6bb7t7zjo0H0Jnt1sJXd0jATk3YXkzE4BUg8obgR2aeYzfYgORUc0FrPBE/o/Xu05ZK7d0wprh4Srf1EuCn9oDUaYKf9Uxw1Gv9nvVoMrdmgHRHhWp04+p4GIzL/35JT0qP2Fyu1XE9G5fl6Q=
  file_glob: true
  file: release/akamai-gtm_*
  on:
    repo: Comcast/akamai-gtm
    tags: true
