language: go

go:
- 1.8
- tip

script:
- make

matrix:
  allow_failures:
  - go: tip

deploy:
  provider: releases
  api_key:
    secure: "hSgFzUg4BAOqG2NeK6cLFVc6aQj1qTjvSxaoj7jPwTLpWfrg+pvAgMjZKJXHV1a/Mp4jH231IcnbdO2hm0ZH77YczLFBP1OhViAFq89wgfDUjRHJ20cfk9QA4DAkO30TKm1tdtnJoyzf3TyVvZsUKb0nc9MN6nRg3JQqGvCb2+FzbOFm7PWPV7zmHU9Io9qXQ4uEx3d/HiRv5rZgo5+eqm44apgbzztEXNWI8wyri7bUNNS0dheDaJAXFxCXh/nyR8ILEOMf8NW53V8gcPA0lHnmdR4M3E0JVZE3QSqMwXObMtrpFP2BBROcfT+q9oNGH36kCPnFrtB+onDMYOzuNhGshu3pYCkXm8FI50U2Y8J9pgJyOkgKYons2JQUXYwzSOtp6NXdyk2t5UvnQABU767/4hQMLQeue0YlnARqUpVkO92XNItfpbSW/ZIpnsGzF0q4LriPSlgzpzwCRl2qUISNKKbo/BM3HfFhOtt0CP9vEmCNoPPV99xG6k9OUNaIArqXNRGqWjK9grYBYKEBxnqDPQ7A4wzPU3L+kt+qjx2MsPGCLcFynhwywR3uq/sE7AKKaimHF2qe/AACUgWuq4srHdTDRrcCMxZFtdrtH85oGrAghAzRAPeHYqZm0fgbuGWrnYd7Kc0Rb53J1SsfEeEKBqUWNifFJsOPn8CwXv8="
  skip_cleanup: true
  file_glob: true
  file: release/akamai-gtm_*
  on:
    repo: Comcast/akamai-gtm
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
